### ISSUE TITLE
On HES gui the "Space" key is not available for choosing for any of the buttons

### ISSUE THREAD

**Issue by paulolc** [HackerSchool/HES#7]
The user can't choose the "Space" key for any of the HES buttons on the HES gui

Steps to reproduce:
- Open HES gui (python -m Computer.gui)
- Choose any HES button
- On the keys dropdown the "Space" key is not available to choose.

**Comment by ric2b** [comment]
I'll add the spacebar :)
If anyone wants other keys that are not included, all the possible keys are shown [here](http://pyautogui.readthedocs.io/en/latest/keyboard.html#keyboard-keys) as indicated by [this line](https://github.com/HackerSchool/HES/blob/master/Computer/settings.py#L12)  on the settings file. Then you just need to add the key you want to the `resources/possible_keys.json` file.

There's some interesting stuff you can do, like using the controller for media controls (volume, skip forward, skip back, play/pause) :)
